summary: "List transactions by sender id "
description: "Try it out for listing all accounts"
consumes:
- "application/json"
produces:
- "application/json"

parameters:
  - in: "path"
    name: "sender"
    type: "integer"
    required: true
responses:
  200:
    description: "Transactions has been listed"
  805:
    descrition: "Transactions couldn find"
